---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: mwrock/Windows2012R2
    transport:
      name: winrm

suites:
  - name: install_msys2
    run_list:
      - recipe[msys2::default]
  - name: install_with_packages
    run_list:
      - recipe[msys2::default]
    attributes:
      msys2:
        packages: ['git', 'tig', 'wget']
